<Window
    x:Class="RevitAddIn_MyProject.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:local="clr-namespace:RevitAddIn_MyProject"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:mechanical="clr-namespace:Autodesk.Revit.DB.Mechanical;assembly=RevitAPI"
    Title="AddSpaceAndZone"
    Width="400"
    Height="480"
    WindowStartupLocation="CenterScreen"
    mc:Ignorable="d">
    <Window.Resources />
    <Grid Margin="10">
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="Auto" MinWidth="120" />
            <ColumnDefinition Width="*" />
            <ColumnDefinition Width="80" />
            <ColumnDefinition Width="4" />
            <ColumnDefinition Width="80" />
        </Grid.ColumnDefinitions>
        <Grid.RowDefinitions>
            <RowDefinition Height="25" />
            <RowDefinition Height="4" />
            <RowDefinition Height="*" />
            <RowDefinition Height="4" />
            <RowDefinition Height="25" />
        </Grid.RowDefinitions>
        <TextBlock
            VerticalAlignment="Center"
            FontWeight="Bold"
            Text="Level:" />
        <ComboBox
            x:Name="levelComboBox"
            Grid.Row="0"
            Grid.Column="1"
            Grid.ColumnSpan="4"
            SelectionChanged="LevelComboBox_SelectionChanged" />
        <TabControl
            Grid.Row="2"
            Grid.Column="0"
            Grid.ColumnSpan="5">
            <TabItem Header="Spaces">
                <Grid Margin="5">
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="100" />
                        <ColumnDefinition Width="*" />
                        <ColumnDefinition Width="100" />
                    </Grid.ColumnDefinitions>
                    <Grid.RowDefinitions>
                        <RowDefinition Height="*" />
                        <RowDefinition Height="4" />
                        <RowDefinition Height="25" />
                    </Grid.RowDefinitions>
                    <ListView
                        x:Name="spacesListView"
                        Grid.RowSpan="1"
                        Grid.ColumnSpan="3"
                        Background="Beige">
                        <ListView.View>
                            <GridView>
                                <GridViewColumn
                                    Width="80"
                                    DisplayMemberBinding="{Binding Path=SpaceName}"
                                    Header="Space" />
                                <GridViewColumn
                                    Width="80"
                                    DisplayMemberBinding="{Binding Path=ZoneName}"
                                    Header="Zone" />
                            </GridView>
                        </ListView.View>
                    </ListView>
                    <Button
                        x:Name="createSpacesButton"
                        Grid.Row="1"
                        Grid.RowSpan="2"
                        Grid.Column="1"
                        Grid.ColumnSpan="2"
                        Height="26"
                        Margin="0,3.667,99.667,-0.333"
                        VerticalAlignment="Top"
                        Click="CreateSpacesButton_Click"
                        Content="Create Spaces" />
                </Grid>
            </TabItem>
            <TabItem Header="Zones">
                <Grid Margin="5">
                    <Grid.RowDefinitions>
                        <RowDefinition Height="*" />
                        <RowDefinition Height="4" />
                        <RowDefinition Height="25" />
                    </Grid.RowDefinitions>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="50" />
                        <ColumnDefinition Width="*" />
                        <ColumnDefinition Width="30" />
                        <ColumnDefinition Width="*" />
                        <ColumnDefinition Width="50" />
                    </Grid.ColumnDefinitions>
                    <TreeView
                        x:Name="zonesTreeView"
                        Grid.RowSpan="1"
                        Grid.ColumnSpan="5"
                        Background="Beige"
                        SelectedItemChanged="ZonesTreeView_SelectedItemChanged">
                        <TreeView.Resources>
                            <HierarchicalDataTemplate DataType="{x:Type local:ZoneSpacesNode}" ItemsSource="{Binding SpaceList}">
                                <TextBlock Text="{Binding ZoneName}" />
                            </HierarchicalDataTemplate>
                            <DataTemplate DataType="{x:Type mechanical:Space}">
                                <TextBlock Text="{Binding Name}" />
                            </DataTemplate>
                        </TreeView.Resources>
                    </TreeView>
                    <Button
                        x:Name="createZoneButton"
                        Grid.Row="2"
                        Grid.Column="1"
                        Click="CreateZoneButton_Click"
                        Content="Create Zone" />
                    <Button
                        x:Name="editZoneButton"
                        Grid.Row="2"
                        Grid.Column="3"
                        Click="EditZoneButton_Click"
                        Content="Edit Zone"
                        IsEnabled="False" />
                </Grid>
            </TabItem>
        </TabControl>
        <Button
            x:Name="OK_Button"
            Grid.Row="4"
            Grid.Column="2"
            Click="OK_Button_Click"
            Content="_OK" />
        <Button
            x:Name="Cancel_Button"
            Grid.Row="4"
            Grid.Column="4"
            Click="Cancel_Button_Click"
            Content="_Cancel" />
    </Grid>
</Window>
